services:
    db:
        image: "mariadb:latest"
        environment:
            - "MARIADB_DATABASE=hospital_db"
            - "MARIADB_PASSWORD=admin"
            - "MARIADB_ROOT_PASSWORD=admin"
            - "MARIADB_USER=admin"
        ports:
            - "3306"
