services:
    hospital_db:
        image: "postgres:latest"
        environment:
            - "POSTGRES_DB=hospital_db"
            - "POSTGRES_PASSWORD=admin"
            - "POSTGRES_USER=admin"
        ports:
            - "5432"
