spring:
    application:
        name: backend

    datasource:
        url: jdbc:postgresql://${DATABASE_HOST:hospital_db}:${DATABASE_PORT:5432}/${DATABASE_NAME:hospital_db}
        username: ${DATABASE_USERNAME:admin}
        password: ${DATABASE_PASSWORD:admin}

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

    jackson:
        property-naming-strategy: SNAKE_CASE

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    ai:
        openai:
            api-key: ${GEMINI_API_KEY}
            base-url: ${GEMINI_BASE_URL}
            chat:
                completions-path: /chat/completions
                options:
                    model: ${GEMINI_MODEL}

server:
    error:
        include-stacktrace: never

app:
    base-path: "/api/v1"
    token:
        expiration-seconds:
            jwt: ${JWT_EXPIRATION_SECONDS}
            refresh: ${REFRESH_TOKEN_EXPIRATION_SECONDS}
            verification: ${VERIFICATION_TOKEN_EXPIRATION_SECONDS}

rsa:
    keys:
        public-key: classpath:keys/jwt_public.pem
        private-key: classpath:keys/jwt_private.pem
